my_red/red_file/config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :users, only: [:new, :create]
  resources :links
  resources :comments

  root 'links#index'

end

my_red/red_file/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
end

my_red/red_file/app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

my_red/red_file/app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  has_many :comments
  validates :email, format: {with: /@/}, uniqueness: true

  def self.signup(email)
    User.create(email: email)
  end
end

my_red/red_file/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    User.find_by(session[:user_id])
  end


end

my_red/red_file/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

my_red/red_file/app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.all
    @link = Link.new
    render :index
  end

  def show
    @link = Link.find(params["id"])
    render :show
  end

  def edit
    @link = Link.find(params["id"])
    render :edit
  end


  def create
    @link = Link.create(link_params)
    redirect_to links_path
  end

  def update
    @link = Link.find(params["id"])
    @link.update(link_params)
    redirect_to links_path(id: @link.id)
  end

  def destroy
    @link = Link.find(params["id"])
    @link.destroy
    redirect_to links_path
  end

  private def link_params
    params.require("link").permit(:name)
  end
end

my_red/red_file/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user
      session[:user_id] = @user.id
      redirect_to root_path(@user)
    else
      redirect_to new_user_path
  end
  end
end

my_red/red_file/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to new_session_path(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  private def user_params
    params.require(:user).permit(:email, :name)
  end
end

my_red/red_file/app/helpers/application_helper.rb
module ApplicationHelper
end

my_red/red_file/app/helpers/comments_helper.rb
module CommentsHelper
end

my_red/red_file/app/helpers/links_helper.rb
module LinksHelper
end

my_red/red_file/app/helpers/sessions_helper.rb
module SessionsHelper
end

my_red/red_file/app/helpers/users_helper.rb
module UsersHelper
end

my_red/red_file/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedFile</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <main>
      <h5>
      Current Red user: <%= current_user.name %>
    </h5>

    <%= yield %>

  </main>
</body>
</html>

my_red/red_file/app/views/links/edit.html.erb
<a href="/">Homepage</a>

my_red/red_file/app/views/links/index.html.erb
<table>
  <tbody>
  <th>
    Status
  </th>
  <td>
<p>
  Are you an existing user?  <%= link_to "Login!",  new_session_path %>
</p>

<p>
  Are you a new user?  <%= link_to "New Account!", new_user_path %>
</p>
</td>

<h1>Welome to My Red</h1>


<% @links.each do |link| %>
<p>
  <%= link_to "#{link.name}", link_path(id: link.id) %>
</p>

<%= link_to "Edit", edit_link_path(id: link.id) %>
<%= link_to "Delete Link", link_path(id: link.id), method: :delete %>

<% end %>

<%= form_for @link do |f| %>
  <%  %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>
</tbody>
</table>

my_red/red_file/app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.text_field :email %>

<%= f.submit "Create User!" %>

<% end %>